sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo apt-get -qq update
install:
  - pip install coverage
  - pip install codeclimate-test-reporter
  - pip install coverage
script:
  - coverage run -m unittest discover -v
